package com.example.videoplayer.data

import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "bookmarks")
data class Bookmark(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0L,
    val videoId: String,
    val positionMs: Long,
    val title: String,
    val note: String = "",
    val timestamp: Long = System.currentTimeMillis()
)

@Entity(tableName = "playlists")
data class Playlist(
    @PrimaryKey
    val id: String,
    val name: String,
    val description: String = "",
    val videoCount: Int = 0,
    val dateCreated: Long = System.currentTimeMillis(),
    val isAutoGenerated: Boolean = false
)

data class VideoChapter(
    val title: String,
    val startMs: Long,
    val endMs: Long
)

data class VideoTrackInfo(
    val id: String,
    val label: String,
    val language: String? = null,
    val isSelected: Boolean = false
)
